### ISSUE TITLE
Enable App Start Profiling

### ISSUE THREAD

**Issue by idosun** [sentry-demos/android#134]
See docs: https://docs.sentry.io/platforms/android/profiling/#app-start-profiling

```
<application>
    <meta-data android:name="io.sentry.dsn" android:value="" />
    <meta-data android:name="io.sentry.traces.sample-rate" android:value="1.0" />
    <meta-data android:name="io.sentry.traces.profiling.sample-rate" android:value="1.0" />
    **<meta-data android:name="io.sentry.traces.profiling.enable-app-start" android:value="true" />**
</application>
```

**Comment by sdzhong** [comment]
Expected behavior: https://demo.sentry.io/profiling/profile/android/ee35c740cc8e40eab88ddc2a87ca9639/flamegraph/?colorCoding=by+system+vs+application+frame&fov=0%2C0%2C1337161856%2C7&query=&sorting=call+order&tid=8957&view=top+down

Expecting profiles like `com.example.vu.android.ThirdPartyContentProvider.onCreate()`


![Image](https://github.com/sentry-demos/android/assets/89550162/f5e16b24-7519-4e8d-9719-2369d17ecbcd)

**Comment by sdzhong** [comment]
Is it possible to send the options to enable app start profiling to the SDK in the app. Or another content provider to start before the others to mock the options used by the SDK? @stefanosiano

**Comment by stefanosiano** [comment]
should be fixed by https://github.com/sentry-demos/android/pull/136
